services:
  traefik:
    image: traefik:v3.0
    container_name: traefik
    restart: unless-stopped
    command:
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
      - --entrypoints.web.forwardedHeaders.insecure=true
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - proxy

  myip:
    build: .
    container_name: myip
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.myip.rule=Host(`myip.2564.me`)
      - traefik.http.routers.myip.entrypoints=web
      - traefik.http.services.myip.loadbalancer.server.port=3000
      - traefik.http.middlewares.myip-ratelimit.ratelimit.average=5
      - traefik.http.middlewares.myip-ratelimit.ratelimit.burst=10
      - traefik.http.middlewares.myip-ratelimit.ratelimit.sourcecriterion.ipstrategy.depth=1
      - traefik.http.routers.myip.middlewares=myip-ratelimit@docker
    networks:
      - proxy

networks:
  proxy:
    external: true