services:
  myip:
    build: .
    container_name: myip
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.myip.rule=Host(`myip.2564.me`)
      - traefik.http.routers.myip.entrypoints=web
      - traefik.http.services.myip.loadbalancer.server.port=3000
      - traefik.docker.network=proxy
    networks:
      - proxy

networks:
  proxy:
    external: true